#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum InputMode {
    #[default]
    Normal,
    CommandLine,
    CellEdit,
    TablePicker,
    CommandPalette,
    GenerateSqlMenu,
    FilePicker,
    Settings,
    Help,
    SqlModal,
    ConnectionSetup,
    ConnectionError,
    ConfirmDialog,
    ConnectionSelector,
    ErTablePicker,
    QueryHistoryPicker,
    JsonDetail,
    JsonEdit,
    CellDetail,
    SqliteDiagnostics,
    RowDetail,
}
